### ISSUE TITLE
Maybe a problem with the buffering ?

### ISSUE THREAD

**Issue by jpbelang** [titorenko/quick-csv-streamer#6] opened 2017-08-09 17:46 UTC
There might be a problem with some of the buffering happening in your code.

When I load from jersey (a 2 gig file), through the request input stream, the stream throw 
a NullPointerException trying to get the next field, here (this returns a null):

uk.elementarysoftware.quickcsv.parser.QuickCSVParser.ByteSliceSpliterator#getNextField

I worked around this by loading the whole stream in a string and using a StringInputStream.  The resulting String is correct, but the parser stops at ~ 33%.  If I do: 

usingBufferSize(string.length())

Everything works fine. But now I have 2 large buffers I was hoping to avoid. 

When I read from disk, your code works fine.  it only fails in my servlet, so I suspect some sort of error around a stream returning a size smaller than expected, and you interpreting it as an end of file.  I haven't found where (if I do, i'll build a PR), but should you be able to fix this, it would be great.

Thanks.

**Comment by titorenko** [comment] 2017-08-10 18:43
Can you please try current snapshot version 0.2.4-SNAPSHOT and let me know if the issue is fixed.

**Comment by titorenko** [comment] 2017-08-19 12:16
Closing the issue due to lack of confirmation, assuming that fix works fine. The fix is released in 0.2.4

**Closed as completed by titorenko** 2017-08-19 12:16 UTC

**Comment by jpbelang** [comment] 2017-08-23 15:02
I does.  Sorry, i was on vacation.  Using a computer on vacation pretty much guarantees that my wife would use my laptop would soon be used as a boat anchor.
